# true color support
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# split panes using \ and -
bind '\' split-window -h
bind '-' split-window -v
unbind '"'
unbind %
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# reload config file
bind r source-file ~/.config/tmux/tmux.conf \; display-message 'Configuration reloaded.'

# switch panes using Alt-hjkl without prefix
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# switch windows using Alt-np without prefix
bind -n M-p previous-window
bind -n M-n next-window

set-option -g status-position top

# right status bar
battery_info="#[fg=black bg=green]#[fg=green bg=black] #(echo $(acpi -b | grep -P -o '[0-9]+(?=%)'))%"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavor 'mocha'
#set -g @catppuccin_window_status_style 'rounded'
set -g @catppuccin_window_right_separator "█ "
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_middle_separator " | "

set -g @catppuccin_window_default_fill "none"

set -g @catppuccin_window_current_fill "all"

set -g @catppuccin_date_time_text " %b-%d %H:%M"
set -g @catppuccin_battery_icon "#(~/.config/tmux/plugins/tmux-battery/scripts/battery_icon_charge.sh) "
set -g @catppuccin_battery_text " #(~/.config/tmux/plugins/tmux-battery/scripts/battery_percentage.sh)"

# Source catppuccin before building status-right
run '~/.config/tmux/plugins/tmux/catppuccin.tmux'

set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_battery}"
set -ag status-right "#{E:@catppuccin_status_date_time}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'

